package assemble

import (
	"fmt"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/dltldn333/WRITEME/internal/workspace"
)

const header = "<!-- Generated by WRITEME. Do not edit this file; edit %s instead. -->\n\n"

var propRe = regexp.MustCompile(`\{\{\s*([^{}]*?)\s*\}\}`)

type Assembler struct {
	ws *workspace.Workspace
}

func New(ws *workspace.Workspace) *Assembler {
	return &Assembler{ws: ws}
}

// Entry assembles one WRITEME.md into the complete README.md content.
func (a *Assembler) Entry(e workspace.Entry) (string, error) {
	body, err := a.render(e.Path, e.Content, nil, nil)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf(header, filepath.Base(e.Path)) + strings.TrimLeft(body, "\n"), nil
}

// render expands one file. values holds the props passed in by the caller, and
// stack holds the parts currently being expanded so cycles can be reported.
func (a *Assembler) render(path, src string, values map[string]string, stack []string) (string, error) {
	src = strings.ReplaceAll(src, "\r\n", "\n")

	fm, body, offset, err := splitFrontmatter(src)
	if err != nil {
		return "", fmt.Errorf("%s: %w", path, err)
	}

	for name := range values {
		if !slices.Contains(fm.Props, name) {
			return "", fmt.Errorf("%s: prop %q is not declared in its frontmatter", path, name)
		}
	}

	lines := strings.Split(body, "\n")
	var fenceCh byte
	var fenceLen int

	for i, line := range lines {
		at := fmt.Sprintf("%s:%d", path, offset+i+1)

		// Code blocks are copied as-is.
		if ch, n, rest := fenceMarker(line); n > 0 {
			switch {
			case fenceCh == 0:
				fenceCh, fenceLen = ch, n
			case ch == fenceCh && n >= fenceLen && strings.TrimSpace(rest) == "":
				fenceCh, fenceLen = 0, 0
			}
			continue
		}
		if fenceCh != 0 {
			continue
		}

		d, ok, err := parseDirective(line)
		if err != nil {
			return "", fmt.Errorf("%s: %w", at, err)
		}
		if ok {
			if lines[i], err = a.expand(d, values, stack); err != nil {
				return "", fmt.Errorf("%s: %w", at, err)
			}
			continue
		}

		if lines[i], err = interpolate(line, values); err != nil {
			return "", fmt.Errorf("%s: %w", at, err)
		}
	}

	return strings.Join(lines, "\n"), nil
}

func (a *Assembler) expand(d directive, values map[string]string, stack []string) (string, error) {
	part, ok := a.ws.Part(d.name)
	if !ok {
		return "", fmt.Errorf("unknown component ::%s (register it under parts in writeme.yaml)", d.name)
	}
	if d.hasLabel {
		return "", fmt.Errorf("::%s: parts do not take a [label]", d.name)
	}

	next := append(slices.Clip(stack), d.name)
	if slices.Contains(stack, d.name) {
		return "", fmt.Errorf("::%s includes itself: %s", d.name, strings.Join(next, " -> "))
	}

	// Attribute values may reference the caller's props, e.g. pkg="{{ pkg }}".
	passed := make(map[string]string, len(d.attrs))
	for k, v := range d.attrs {
		resolved, err := interpolate(v, values)
		if err != nil {
			return "", fmt.Errorf("::%s attribute %s: %w", d.name, k, err)
		}
		passed[k] = resolved
	}

	out, err := a.render(part.Path, part.Content, passed, next)
	if err != nil {
		return "", fmt.Errorf("::%s: %w", d.name, err)
	}
	return strings.Trim(out, "\n"), nil
}

func interpolate(s string, values map[string]string) (string, error) {
	var missing error

	out := propRe.ReplaceAllStringFunc(s, func(match string) string {
		name := propRe.FindStringSubmatch(match)[1]
		v, ok := values[name]
		if !ok && missing == nil {
			missing = fmt.Errorf("{{ %s }} has no value", name)
		}
		return v
	})
	return out, missing
}

// fenceMarker recognises a ``` or ~~~ code fence line and returns the fence
// character, its length, and the text after it.
func fenceMarker(line string) (ch byte, n int, rest string) {
	s := strings.TrimLeft(line, " ")
	if len(line)-len(s) > 3 || s == "" || (s[0] != '`' && s[0] != '~') {
		return 0, 0, ""
	}
	for n < len(s) && s[n] == s[0] {
		n++
	}
	if n < 3 {
		return 0, 0, ""
	}
	return s[0], n, s[n:]
}
