package assemble

import (
	"strings"
	"testing"

	"github.com/dltldn333/WRITEME/internal/workspace"
)

const hdr = "<!-- Generated by WRITEME. Do not edit this file; edit WRITEME.md instead. -->\n\n"

var testParts = []workspace.Part{
	{Name: "BASE", Path: "BASE.md", Content: "## License\n\nMIT\n"},
	{Name: "install", Path: "parts/install.md", Content: "---\nprops:\n  - pkg\n---\n\nnpm i {{ pkg }}\n"},
	{Name: "outer", Path: "parts/outer.md", Content: "---\nprops: [pkg]\n---\n## Install\n::install{pkg=\"{{ pkg }}\"}\n"},
	{Name: "optional", Path: "parts/optional.md", Content: "---\nprops: [unused]\n---\nstatic\n"},
	{Name: "loopA", Path: "parts/a.md", Content: "::loopB\n"},
	{Name: "loopB", Path: "parts/b.md", Content: "::loopA\n"},
	{Name: "self", Path: "parts/self.md", Content: "::self\n"},
	{Name: "broken", Path: "parts/broken.md", Content: "line one\n::nope\n"},
	{Name: "unclosed", Path: "parts/unclosed.md", Content: "---\nprops: [a]\n"},
}

func assembleEntry(content string) (string, error) {
	a := New(&workspace.Workspace{Root: ".", Parts: testParts})
	return a.Entry(workspace.Entry{Dir: ".", Path: "WRITEME.md", Output: "README.md", Content: content})
}

func TestEntry(t *testing.T) {
	tests := []struct {
		name  string
		entry string
		want  string
	}{
		{name: "plain markdown", entry: "# Hi\n", want: "# Hi\n"},
		{name: "entry frontmatter removed", entry: "---\nprops: []\n---\n\n# Hi\n", want: "# Hi\n"},
		{name: "part inserted", entry: "# Hi\n\n::BASE\n", want: "# Hi\n\n## License\n\nMIT\n"},
		{name: "props passed", entry: "::install{pkg=\"core\"}\n", want: "npm i core\n"},
		{name: "nested part forwards props", entry: "::outer{pkg=\"cli\"}\n", want: "## Install\nnpm i cli\n"},
		{name: "declared prop may go unused", entry: "::optional\n", want: "static\n"},
		{name: "backtick fence untouched", entry: "```md\n::BASE\n{{ x }}\n```\n", want: "```md\n::BASE\n{{ x }}\n```\n"},
		{name: "tilde fence ignores inner backticks", entry: "~~~\n```\n::BASE\n~~~\n", want: "~~~\n```\n::BASE\n~~~\n"},
		{name: "text after fence is processed", entry: "```\ncode\n```\n::BASE\n", want: "```\ncode\n```\n## License\n\nMIT\n"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := assembleEntry(tt.entry)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != hdr+tt.want {
				t.Errorf("\n got: %q\nwant: %q", got, hdr+tt.want)
			}
		})
	}
}

func TestEntryErrors(t *testing.T) {
	tests := []struct {
		name  string
		entry string
		want  []string
	}{
		{name: "unknown component", entry: "::nope\n", want: []string{"WRITEME.md:1:", "unknown component ::nope"}},
		{name: "entry prop has no value", entry: "# {{ title }}\n", want: []string{"{{ title }} has no value"}},
		{name: "declared prop not passed", entry: "::install\n", want: []string{"parts/install.md:6:", "{{ pkg }} has no value"}},
		{name: "undeclared prop passed", entry: "::BASE{x=\"1\"}\n", want: []string{`prop "x" is not declared`}},
		{name: "cycle", entry: "::loopA\n", want: []string{"includes itself", "loopA -> loopB -> loopA"}},
		{name: "self include", entry: "::self\n", want: []string{"self -> self"}},
		{name: "label on part", entry: "::BASE[hi]\n", want: []string{"do not take a [label]"}},
		{name: "malformed component", entry: "::BASE{x=1}\n", want: []string{"bad attribute"}},
		{name: "line number after frontmatter", entry: "---\nprops: []\n---\n\n::nope\n", want: []string{"WRITEME.md:5:"}},
		{name: "error inside part points at part line", entry: "ok\n::broken\n", want: []string{"WRITEME.md:2:", "parts/broken.md:2:", "::nope"}},
		{name: "part frontmatter not closed", entry: "::unclosed\n", want: []string{"parts/unclosed.md", "not closed"}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := assembleEntry(tt.entry)
			if err == nil {
				t.Fatal("expected an error, got none")
			}
			for _, w := range tt.want {
				if !strings.Contains(err.Error(), w) {
					t.Errorf("error %q should contain %q", err, w)
				}
			}
		})
	}
}
