package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/dltldn333/WRITEME/internal/assemble"
	"github.com/dltldn333/WRITEME/internal/config"
	"github.com/dltldn333/WRITEME/internal/workspace"
)

const usageText = `WRITEME builds README.md files for a monorepo.

Text that repeats across packages lives in parts and is written once. BASE.md
is the main part: writeme init creates it, registers it, and most packages end
with ::BASE. Each package keeps only what is unique to it in WRITEME.md and pulls
parts in with ::name, where name is the part's file name without .md.
README.md is generated: edit WRITEME.md or the parts instead.

Usage:
  writeme init     Create writeme.yaml, WRITEME.md, and BASE.md in this folder
  writeme build    Write a README.md next to every WRITEME.md below this folder
  writeme help     Show this help

Example:
  writeme.yaml                     registers parts (init adds BASE.md)
    parts:
      - BASE.md
      - parts/install.md

  BASE.md                          main part, shared by every package
    ## License
    MIT

  parts/install.md                 extra part that takes a value
    ---
    props:
      - pkg
    ---
    ## Install
    Run: npm install {{ pkg }}

  packages/core/WRITEME.md         unique to this package
    # @acme/core
    Helpers for dates and retries.

    ::install{pkg="@acme/core"}

    ::BASE

  writeme build  ->  packages/core/README.md
    <!-- Generated by WRITEME. ... -->

    # @acme/core
    Helpers for dates and retries.

    ## Install
    Run: npm install @acme/core

    ## License
    MIT

Docs: https://github.com/dltldn333/WRITEME
`

func usage(w io.Writer) {
	fmt.Fprint(w, usageText)
}

func runBuild() error {
	cfg, err := config.Load(".")
	if err != nil {
		return err
	}

	ws, err := workspace.Load(".", cfg)
	if err != nil {
		return err
	}

	a := assemble.New(ws)
	outputs := make([]string, len(ws.Entries))
	for i, e := range ws.Entries {
		if outputs[i], err = a.Entry(e); err != nil {
			return err
		}
	}

	// Write only after every entry assembled, so one bad file leaves nothing half-built.
	for i, e := range ws.Entries {
		if err := os.WriteFile(filepath.Join(ws.Root, e.Output), []byte(outputs[i]), 0o644); err != nil {
			return err
		}
		fmt.Println("Wrote", e.Output)
	}

	return nil
}

func main() {
	if len(os.Args) < 2 {
		usage(os.Stderr)
		os.Exit(1)
	}

	switch os.Args[1] {
	case "init":
		created, err := config.Init(".")
		if err != nil {
			fmt.Fprintln(os.Stderr, "writeme:", err)
			os.Exit(1)
		}
		for _, name := range created {
			fmt.Println("Created", name)
		}
	case "build":
		if err := runBuild(); err != nil {
			fmt.Fprintln(os.Stderr, "writeme:", err)
			os.Exit(1)
		}
	case "help", "-h", "--help":
		usage(os.Stdout)
	default:
		fmt.Fprintf(os.Stderr, "writeme: unknown command %q\n\n", os.Args[1])
		usage(os.Stderr)
		os.Exit(1)
	}
}
